name: Continuous Integration
on:
  schedule:
    - cron: '0 0 * * *'
  pull_request:
  push:
    branches:
      - master
jobs:
  build:
    strategy:
      matrix:
        include:
          - os: macos-12
            test: test
          - os: windows-2022
            test: test
          - os: ubuntu-22.04
            test: test-headless
    runs-on: ${{ matrix.os }}
    env:
      CI: true
    steps:
    - uses: actions/checkout@v1
    - uses: actions/setup-node@v1
      with:
        node-version: 18
    - run: npm ci
    - run: npm run build
    - run: npm run ${{ matrix.test }}
